--Creating table tickers
CREATE TABLE IF NOT EXISTS public.tickers
(
    ticker_id INT GENERATED BY DEFAULT AS IDENTITY,
    symbol varchar NOT NULL,
    CONSTRAINT pk_tickers PRIMARY KEY (ticker_id)
)

TABLESPACE pg_default;

ALTER TABLE public.tickers
    OWNER to postgres;



--Creating table ticker_info


CREATE TABLE IF NOT EXISTS public.ticker_info
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    ticker_id INT NOT NULL,
    volume character varying(64) COLLATE pg_catalog."default" NOT NULL,
    volume_weighted character varying(64) COLLATE pg_catalog."default" NOT NULL,
    open_price character varying(64) COLLATE pg_catalog."default" NOT NULL,
    close_price character varying(64) COLLATE pg_catalog."default" NOT NULL,
    highest_price character varying(64) COLLATE pg_catalog."default" NOT NULL,
    lowest_price character varying(64) COLLATE pg_catalog."default" NOT NULL,
    request_datetime date NOT NULL,
    number_of_transactions integer NOT NULL,
    CONSTRAINT ticker_info_pkey PRIMARY KEY (id),
    CONSTRAINT "FK_ticker_info_tickers_ticker_id" FOREIGN KEY (ticker_id)
        REFERENCES public.tickers (ticker_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)

TABLESPACE pg_default;

ALTER TABLE public.ticker_info
    OWNER to postgres;